name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  msrv-check:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Get MSRV
        run: |
          RUST_MSRV="$(cat cargo-near/Cargo.toml | sed -n 's/rust-version *= *"\(.*\)"/\1/p')"
          echo "RUST_MSRV=$RUST_MSRV" >> $GITHUB_ENV

      - name: "Install ${{ env.RUST_MSRV }} toolchain (MSRV)"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_MSRV }}
          default: true

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install --assume-yes libudev-dev

      - name: downgrade crates to support older Rust toolchain
        if: matrix.toolchain == '1.69.0'
        run: |
          cargo update -p anstyle --precise 1.0.2
          cargo update -p clap --precise 4.3.24
          cargo update -p clap_lex --precise 0.5.0

      - name: Cargo check
        run: cargo check -p cargo-near

  tests:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      # Remove this whole block once nearcore supports Rust 1.70.0+
      # https://github.com/near/nearcore/issues/9143
      - name: "Install 1.69.0 toolchain"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.69.0
          default: true

      - name: Install `wasm32-unknown-unknown`
        run: rustup target add wasm32-unknown-unknown

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install --assume-yes libudev-dev

      - name: Run tests
        run: cargo test --workspace --verbose

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Check Formatting
        run: cargo fmt -- --check

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install --assume-yes libudev-dev

      - name: Check Clippy
        run: cargo clippy --tests -- -Dclippy::all

  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Audit Tool
        run: cargo install cargo-audit

      - name: Run Audit Tool
        run: cargo audit --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2022-0093
